### ISSUE TITLE
Epoch1训练越来越耗时

### ISSUE THREAD

**Issue by qiutzh** [JaySaligia/PPT#1]
作者你好，能提供下python包依赖环境吗？训练时使用的什么设备呢？我用3080上使用ICEWS05数据集跑了下代码，发现模型在运行第一个Epoch时，中途消耗的时间会越来越长，内存也会被占满，后面直接就卡死。另外，我是指定的一个显卡。想问下作者有遇到类似情况吗，可能的原因是什么？

**Comment by JaySaligia** [comment]
你好，已经在仓库里新增了requirement文件。我们的训练是在python 3.6.8和3090上训练的，ICEWS05是这几个数据集中最大的，如果内存溢出可以尝试降低最大采样个数和采样长度试试（--max_sample 8 --seq_len 128），如果是指定显卡也是可以的，我们包含了指定显卡训练的功能。

**Comment by qiutzh** [comment]
> 你好，已经在仓库里新增了requirement文件。我们的训练是在python 3.6.8和3090上训练的，ICEWS05是这几个数据集中最大的，如果内存溢出可以尝试降低最大采样个数和采样长度试试（--max_sample 8 --seq_len 128），如果是指定显卡也是可以的，我们包含了指定显卡训练的功能。

嗯嗯是的，数据多显存小，降低数据量后运行正常。
