### ISSUE TITLE
Dataset label

### ISSUE THREAD

**Issue by SRL94** [JaySaligia/PPT#2]
Hi,

Very interesting work and thank you for sharing your code. One question about the dataset. Do you have the real name of the timestamp? For example, the first valid fact of dataset ICEWS18: 
563  	5    	562	5760	0
563 and 562 can be found in "entity2id.txt"; 5 can be found in "rel2id.txt". How about 5760 and 0? Are they timestamps?

Thank you.

Best regards

**Comment by JaySaligia** [comment]
Thank you for your attention to our work. 

The timestamps in the dataset refer to the time interval from the first snapshot (timestamp=0). Specifically, the timestamps do not correspond to a specific real-world time, but rather represent the time interval from the first snapshot. For example, 5760 represents 5760 hours from the quadruple to the first snapshot in the dataset (the time granularity of ICEWS18 is an hour). We listed the time granularity of each dataset in Table 1 of our paper.

We only use the first four numbers of each row in datasets, which are (head entity, relation, tail entity, timestamp). The last number is a label in the dataset and does not need to be used.

I hope this could help you.

Best regards

**Comment by SRL94** [comment]
Thank you for the clarification. Could you please inform me of the method used to count the hours for each quadruple? I checked the [website](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/28075), but the duration information seems not available.

**Comment by JaySaligia** [comment]
I do not understand what 'count the hours for each quadruple' exactly means. If it refers to the timestamps in each quadruple and the time interval between each snapshot is fixed (24 hours in ICEWS18). However, I am not entirely clear on the specific method used to construct the dataset as I am using open-source data.

**Comment by SRL94** [comment]
Thank you!
