### ISSUE TITLE
如何使用uncased进行实验

### ISSUE THREAD

**Issue by meteorlin** [JaySaligia/PPT#3]
作者您好！您的工作非常具有启发性！
我们想请教您如何使用BERT-base-uncased进行实验？我们现在将基座PLM改为uncased之后（词表没有改，使用的是您项目中提供的词表），模型似乎不能正常运行。（如下图所示，输出的结果基本上都是0）
![image](https://github.com/JaySaligia/PPT/assets/49402403/ab98d14d-41d9-4cae-9d3c-a19002c31122)

**Comment by JaySaligia** [comment]
您好！
您需要在bert文件下新建一个目录，例如，bert_base_uncased_ICEWS14，然后去下载uncase-bert和对应的vocab.txt然后将cased目录下已生成的special_tokens_map.json文件放入该目录下，并修改vocab.txt前几项如下图所示。
![QQ截图20230804102222](https://github.com/JaySaligia/PPT/assets/31055972/d8b1884d-6e7f-4d83-8ce0-bd3faaaad732)

**Comment by meteorlin** [comment]
感谢您的答复！我下来尝试一下。
此外，我们在运行ICEWS05-15后（cased为基座）输出的结果非常低，但是运行14和18就输出正常。不知道您有没有遇到过这个问题？
这是我们运行的命令
```bash
python PPT.py --dataset ICEWS05 --gpu 2 --max_sample 16 --seq_len 256 --m train --batch_size 32 --mi 0 --max_epochs 5
python PPT.py --dataset ICEWS05 --gpu 2 --max_sample 16 --seq_len 256 --m eval --batch_size 32 --mi 0 --epoch 0
python PPT.py --dataset ICEWS05 --gpu 2 --max_sample 16 --seq_len 256 --m test --batch_size 32 --mi 0 --epoch 0
```
结果为：
![image](https://github.com/JaySaligia/PPT/assets/49402403/ebc07cca-1a06-4d5e-9e4f-ff83612bb73e)
预训练得到的检查点应该也是正常的：
![image](https://github.com/JaySaligia/PPT/assets/49402403/28b875a3-5ea6-4e3d-82d2-21f46999a2d5)

**Comment by JaySaligia** [comment]
您尝试将tokenizer_config.json和tokenizer.json删除后再试试，有时模型不能正常生成tokenizer文件，具体原因我们也还在探究中

**Comment by meteorlin** [comment]
好的我试试！期待您的更新！
欸我这才注意到05-15内置了一个tokenizer.json

**Comment by meteorlin** [comment]
> 您尝试将tokenizer_config.json和tokenizer.json删除后再试试，有时模型不能正常生成tokenizer文件，具体原因我们也还在探究中

我们尝试了您提供的建议，模型能够正常运行了。后续我们再测试PLM改为uncased的情况。

**Comment by Sun-spots** [comment]
作者您好！您的工作非常具有启发性！
我们想请教您我在使用BERT-base-cased进行实验时，下载了模型和vocab.txt，跑出来的结果为0，是什么原因呢
![62ddf6076bc5c05e81389b0d5bb1742](https://github.com/JaySaligia/PPT/assets/97075140/c0080289-9329-4340-9ad4-47b7ab71e48f)
（如下图所示，输出的结果基本上都是0）
