### ISSUE TITLE
报告的指标是否包括逆关系

### ISSUE THREAD

**Issue by meteorlin** [JaySaligia/PPT#4]
作者您好！请问您论文中报告的指标是否包含了逆关系的预测，即预测头实体的性能？如果没有，是什么原因而支持您不执行该操作呢？否则，论文中报告的性能是否不公平？（以ICEWS14为例，我们可以参考每个时间片上具有更多三元组的ICEWS18，可以发现参与测试的三元组越多，模型的性能一般会越低）
我们提出该疑问的理由是：
1. 我们在当前存储库中找不到添加逆关系的代码。
2. 据我所知，RE-GCN、RE-Net等模型（包括后续提出的CEN，您论文中没有进行对比）报告的指标都是包括预测头实体的，具体可以参考RE-GCN同作者的工作CEN论文中的`Implementation Details`一节。他们的具体做法是预测逆关系的尾实体，即预测原关系的头实体。下面这段代码展示了RE-GCN在测试集上的预测行为：
![image](https://github.com/JaySaligia/PPT/assets/49402403/72354b30-42b5-41f6-bf0e-84b4a1018458)

**Comment by ZifengDing** [comment]
我也想问这个问题。我没找到subject prediction的部分。一般来说tkg forecasting的模型object prediction都比subject prediction的结果好很多，所以这篇文章的结果其实问题很大。不知道为什么可以进acl findings。如果作者可以给出合理解释那就ok。
还有就是如果作者把逆关系考虑进去的话，在这篇文章的prompt里，逆关系的文字描述应该是要人工手写成被动形式的。我没有找到类似的代码。

**Comment by ZifengDing** [comment]
不是想diss作者。这篇文章的novelty很好，但是实验的setting问题确实很大。希望作者可以补上subject prediction的结果。否则以后新的文章在review的时候就很可能被拿着这篇文章的结果攻击，会非常不公平。

**Comment by JaySaligia** [comment]
你好，感谢你对我们工作的关注。
我们检查了上传至github的代码，这个版本确实没有包含对头实体的预测。我们分别有对尾实体和头实体进行实验的文件，在上传至github整理代码的时候只复制了预测尾实体的那份代码文件，现在已在最新版本将原代码合并并更正。
另外，关于你提出的问题，我们也是手动将逆关系转换为被动时态（例如A make a visit to B 对应的为B be mada a visit to A），在我们的预研实验中，如果不使用逆关系，而是通过固定尾实体的方法取样，对原来的头实体进行预测，效果不太行，我们分析的可能原因是关系的语句很重要，位于尾实体位置的实体才能更好地获取知识，因此我们也是类似RE-GCN的方式构造逆关系（即没有在原三元组的基础上直接预测头实体，而是交换头尾实体的位置），由于没有办法直接地生成类似r变为r-1的方式，所以我们手动编写了被动时态的关系。
此外，由于我们的实验设置是基于raw metric的设置，现在主流方法是使用time-aware filter的方式，我们也将在近期更新这方面的代码和结果，欢迎继续关注我们的工作。

**Comment by ZifengDing** [comment]
Hi, 感谢回复。因为我需要把你们的工作放到我新的工作中去，我是这么改的。我把每个relation的text之前加了Inversed。比如说Defend Verbally的逆关系我就写成Inversed Defend Verbally。然后time aware filter我也写好了。把所有的预测都变成object prediction，sample的话还是对subject entity进行采样。我自己跑出来的实验结果是符合预期的。请问作者你觉得这样改是不是符合你们的思路呢？

**Comment by JaySaligia** [comment]
你好，我觉得这是可行的，我们也尝试过类似的方案，是直接在逆关系之前加上一个类似于[INVERSE]的token。

**Comment by TCcjx** [comment]
> 你好，感谢你对我们工作的关注。 我们检查了上传至github的代码，这个版本确实没有包含对头实体的预测。我们分别有对尾实体和头实体进行实验的文件，在上传至github整理代码的时候只复制了预测尾实体的那份代码文件，现在已在最新版本将原代码合并并更正。 另外，关于你提出的问题，我们也是手动将逆关系转换为被动时态（例如A make a visit to B 对应的为B be mada a visit to A），在我们的预研实验中，如果不使用逆关系，而是通过固定尾实体的方法取样，对原来的头实体进行预测，效果不太行，我们分析的可能原因是关系的语句很重要，位于尾实体位置的实体才能更好地获取知识，因此我们也是类似RE-GCN的方式构造逆关系（即没有在原三元组的基础上直接预测头实体，而是交换头尾实体的位置），由于没有办法直接地生成类似r变为r-1的方式，所以我们手动编写了被动时态的关系。 此外，由于我们的实验设置是基于raw metric的设置，现在主流方法是使用time-aware filter的方式，我们也将在近期更新这方面的代码和结果，欢迎继续关注我们的工作。

想请问一下作者，目前的代码是否包含time-aware filter的方式？还是说仍然采用的raw metric？
