### ISSUE TITLE
PreBertDataset.__getitem__ 中的 input_ids处理问题

### ISSUE THREAD

**Issue by y17733806775** [JaySaligia/PPT#8]
`        for i, id in enumerate(input_ids):
            id = int(id - 1)
            if 0 <= id < 33:
                row = id // 2
                col = (id % 2) * 2
                input_ids[i] = path[row][col] + token_begin`
作者我想请教您一个问题。这段处理是什么意思呢，token_id减一对应的token不就变了吗？token_id在0~32之间对应哪些token呢，我查阅了官方文档并没有找到结果。

**Comment by JaySaligia** [comment]
你好，感谢你对我们工作的关注。
这里是我们在工作中对于Bert tokenizer的一个加速方法，我们在实验时发现在使用bert时，大量时间会被花费在tokenizer中。具体的原理如下：我们在vocab.txt文件中编写了前若干个token，这些token形如[ENTi]，其中i表示在输入至bert时出现的第i个实体，此处仅仅是bert中出现的顺序，与具体的对应的实体无关，我们在path中保存了实体真实的序号，通过+token_begin的方式映射到真正输入至bert的token。
这样bert只需要先将我们输入中的预留词[ENTi]转换为对应的位置靠前的token，再将这些token映射至真实实体对应的token，就可以避免在tokenizer时花费大量的搜索时间。
